---
title: "data viz"
description: |
  A short description of the post.
author:
  - name: Brendan McGovern
    url: {}
date: 2022-03-08
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(here)
library(tidyverse)
library(janitor)
library(ggplot2)
library(dplyr)
```

## History of Mono Lake levels (1850 - 2017) with important ecological indicators and major legal milestones

```{r}
mono_lake <- read_csv((file = 'data/mono_lake_annual_levels.csv'), skip = 5)
```


```{r}
mono_lake_clean <- mono_lake %>% 
  clean_names() 
```


```{r, fig.cap = "Historic lake levels of Mono Lake from 1850 - 2017. Mono Lake has suffered ecologically from diversions of water toward Los Angeles. As the lake levels have dropped, the lake has experienced negative ecological consequences. As the lake level decreases to 6,377ft above sea level (yellow line), land bridges emerge between the mainland and islands allowing predators to access major bird nesting sites. If lake levels decreased below 6,360ft (dark red line), lake salinity would reach 120 g/L decreasing brine shrimp populations and the California gull populations that depend on brine shrimp. At 6,350ft (black line) the impact of salinity would be above 150 g/L. In 1979 (highlighted in dark blue), Public Trust Suit brought before the Mono County Superior Court by the National Audubon Society, Mono Lake Committee, and others. This process was the cornerstone of the legal efforts to protect Mono Lake from diversion by the City of Los Angeles Department of Water and Power (DWP). Eventually the case was carried up to the California Supreme Court. In 1983 (highlighted in purple), the California Supreme Court ruled that water diversions by the LA DWP violated the Public Trust Doctrine - stating that certain resources are too valuable to be privately owned and must remain available for public use - invalidating LA's prior water allocation decisions of the streams feeding the lake.In 1994 (highlight in red), the State Water Resouces Control Board issued Decision 1631, a landmark decision amending DWP's water diversion licenses in the Mono Basin to proctect fisheries and ensure the lake's public trust values were protected (Data: Mono Basin Clearinghouse)."}

mono_lake_clean %>% 
  ggplot(aes(x = year, y = lake_level_feet_above_sea_level)) +
  geom_line(size = 1.25, color = "cyan4", alpha = 1) +
  geom_ribbon(aes(ymin = -Inf, ymax = lake_level_feet_above_sea_level), fill = "darkcyan", alpha = 0.2) +
  scale_x_continuous(limits = c(1850, 2019), breaks = c(1850, 1875, 1900, 1925, 1950, 1975, 2000, 2017), expand = c(0,0)) +
  geom_hline(yintercept = 6377, color = "goldenrod2", size = 1) +
  geom_hline(yintercept = 6360, color = "firebrick", size = 1) + 
  geom_hline(yintercept = 6350, color = "black", size = 1) +
  geom_point(data = mono_lake_clean, fill = "darkcyan", size = 1) +
  annotate(geom = "point", x = 1979, y = 6373.40, color = "darkblue", size = 2, hjust =0) +
  annotate("text", x = 1979, y = 6410, color = "darkblue", label = "Public Trust Suit initiates") +
  geom_segment(aes(x = 1979, y = 6373.40, xend = 1979, yend = 6406), color = "darkblue") +
  annotate(geom = "point", x = 1983, y = 6378.60, color = "darkmagenta", size = 2, hjust =0) +
  annotate("text", x = 1983, y = 6400, color = "darkmagenta", label = "Public Trust Doctrine") +
  geom_segment(aes(x = 1983, y = 6378.60, xend = 1983, yend = 6398), color = "darkmagenta") +
  annotate(geom = "point", x = 1994, y = 6374.60, color = "red", size = 2, hjust =0) +
  annotate("text", x = 1994, y = 6390, color = "red", label = "Decision 1631") +
  geom_segment(aes(x = 1994, y = 6374.60, xend = 1994, yend = 6388), color = "red") +
  labs(x = "Year", y = "Lake level (in ft above sea level)", title = "Mono Lake: History of Lake Levels and Major Court Cases", subtitle = "1850 - 2017") +
  theme_minimal()
```
